import { Modal } from '@/Components/Modal'
import { UserModal } from '@/Components/UserModal/UserModal'

import './globals.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Ordering Meal App',
  description: 'Generated by Ryosuke Saito'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="no-scrollbar bg-[#F8F8F8]">
        {children}
        <Modal />
        <UserModal />
      </body>
    </html>
  )
}
